.TH dipha-dualize "1" "January 2016" "DIPHA 2.1.0" "User Commands"
.SH NAME
dipha-dualize \- Convert a file from boundary format to coboundary format
.SH SYNOPSIS
\fBdipha-dualize\fR [\fI\,options\/\fR] \fI\,input_filename output_filename\/\fR
.SH DESCRIPTION
This program converts a file from boundary format (required for primal computation)
to coboundary format (required for dual computation).
.SH OPTIONS
.TP
\fB\-\-help\fR
prints this screen
.TP
\fB\-\-benchmark\fR
prints timing info
.SH AUTHORS
\fBdipha\fR is written IST Austria, contributed by: Jan Reininghaus.
.PP
This manual page was written by Ippei Obayashi <ohai@kmc.gr.jp>.
.SH SEE ALSO
https://github.com/DIPHA/dipha

